spring.application.name=backend-java

# Ligar a base de dados Postgre
spring.datasource.url=jdbc:postgresql://localhost:5432/studybuddy
spring.datasource.username=admin
spring.datasource.password=admin

# Criar/Atualizar automaticamente tabelas
spring.jpa.hibernate.ddl-auto=update


# Mostrar no terminal o que foi criado
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true